[package]
name = "Common"
version = "1.0.0"
published-at = "0xf9c8ff62cf2115c55aecb91d29c46c1b3533b02ae961547ab93a028dec837250"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "1.0.1"}

[addresses]
common =  "0xf9c8ff62cf2115c55aecb91d29c46c1b3533b02ae961547ab93a028dec837250"
sui= "0x02"